PresentationLayer/Controllers/DepartamentoController.cs
using EntitiesLayer;
using LogicBusinessLayer;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class DepartamentoController : Controller
    {
        DepartamentosBusiness departamentosBusiness = new DepartamentosBusiness();
        // GET: Departamento
        public ActionResult Index()
        {
            return View(departamentosBusiness.ShowDepartments());
        }

        // GET: Departamento/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departamento/Create
        [HttpPost]
        public ActionResult Create(Departamento departamento)
        {
            try
            {
                departamento.Siglas = departamento.Siglas.ToUpper();
                departamentosBusiness.InsertDepartments(departamento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Departamento/Edit/5
        public ActionResult Edit(int? id)
        {
            return View(departamentosBusiness.FindDepartamento(id));
        }

        // POST: Departamento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Departamento departamento)
        {
            try
            {
                departamento.Siglas = departamento.Siglas.ToUpper();
                departamentosBusiness.UpDateDepartments(departamento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Departamento/Delete/5
        public ActionResult Delete(int? id)
        {
            return View(departamentosBusiness.FindDepartamento(id));
        }

        // POST: Departamento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Departamento departamento)
        {
            try
            {

                departamentosBusiness.DeleteDepartments(departamento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PresentationLayer/Views/Departamento/Create.cshtml
@model EntitiesLayer.Departamento

@{
    ViewBag.Title = "Create";
}

<h2 class="display-3 my-3 text-center">Crear Departamento</h2>

<div class="row justify-content-center">
    <div class="col-12 col-md-8 text-center">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="">
                <hr />
                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", placeholder = "Nombre" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Siglas, new { htmlAttributes = new { @class = "form-control", placeholder = "Siglas" } })
                        @Html.ValidationMessageFor(model => model.Siglas, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    <div class="col">
                        <input type="submit" value="Crear" class="btn btn-primary btn-block" />
                        <a href="/Departamento/Index" class="btn btn-primary btn-block">Volver</a>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/Departamento/Delete.cshtml
@model EntitiesLayer.Departamento

@{
    ViewBag.Title = "Delete";
}

<h2 class="display-3 my-3 text-center">Eliminar Departamento</h2>

<div class="row justify-content-center">
    <div class="col-12 d-flex justify-content-center">
        <div class="card text-white bg-danger mb-3" style="max-width: 20rem;">
            <div class="card-header">Eliminar</div>
            <div class="card-body">
                <h5 class="card-title">
                    @Html.DisplayNameFor(model => model.Nombre):
                    @Html.DisplayFor(model => model.Nombre)
                    <br />
                    @Html.DisplayNameFor(model => model.Siglas):
                    @Html.DisplayFor(model => model.Siglas)
                </h5>
                <p class="card-text">¿Está seguro de que desea eliminar? Una vez hecho no podra recuperar los datos.</p>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a href="/Departamento/Index" class="btn btn-primary">Volver</a>
        </div>
    }
</div>

PresentationLayer/Views/Departamento/Edit.cshtml
@model EntitiesLayer.Departamento

@{
    ViewBag.Title = "Edit";
}

<h2 class="display-3 my-3 text-center">Editar Departamento</h2>


<div class="row justify-content-center">
    <div class="col-12 col-md-8 text-center">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.HiddenFor(model => model.ID)

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", placeholder = "Nombre" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        @Html.EditorFor(model => model.Siglas, new { htmlAttributes = new { @class = "form-control", placeholder = "Siglas" } })
                        @Html.ValidationMessageFor(model => model.Siglas, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    <div class="col">
                        <input type="submit" value="Editar" class="btn btn-success btn-block" />
                        <a href="/Departamento/Index" class="btn btn-primary btn-block">Volver</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/Departamento/Index.cshtml
@model IEnumerable<EntitiesLayer.Departamento>

@{
    ViewBag.Title = "Departamentos";
}

<h2 class="display-2 my-3">Departamentos</h2>

<div class="my-2">

    <a href="/Departamento/Create" class="btn btn-primary">Crear</a>

</div>

<table class="table table-borderless table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Siglas)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Siglas)
                </td>
                <td class="d-flex">
                    <a href="@Url.Action("Edit", "Departamento")/@item.ID" class="btn btn-success ml-1">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="@Url.Action("Delete", "Departamento")/@item.ID" class="btn btn-danger ml-1">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts{

    <script>

        $(document).ready(function () {
            $(".table").DataTable({
                language: {
                    processing: "Procesando...",
                    lengthMenu: "Mostrar _MENU_ registros",
                    zeroRecords: "No se encontraron resultados",
                    emptyTable: "Ningún dato disponible en esta tabla",
                    infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    infoFiltered: "(filtrado de un total de _MAX_ registros)",
                    search: "Buscar:",
                    infoThousands: ",",
                    loadingRecords: "Cargando...",
                    paginate: {
                        first: "Primero",
                        last: "Último",
                        next: "Siguiente",
                        previous: "Anterior",
                    },
                    aria: {
                        sortAscending: ": Activar para ordenar la columna de manera ascendente",
                        sortDescending:
                            ": Activar para ordenar la columna de manera descendente",
                    },
                    buttons: {
                        copy: "Copiar",
                        colvis: "Visibilidad",
                        collection: "Colección",
                        colvisRestore: "Restaurar visibilidad",
                        copyKeys:
                            "Presione ctrl o u2318 + C para copiar los datos de la tabla al portapapeles del sistema. <br /> <br /> Para cancelar, haga clic en este mensaje o presione escape.",
                        copySuccess: {
                            1: "Copiada 1 fila al portapapeles",
                            _: "Copiadas %d fila al portapapeles",
                        },
                        copyTitle: "Copiar al portapapeles",
                        csv: "CSV",
                        excel: "Excel",
                        pageLength: {
                            "-1": "Mostrar todas las filas",
                            1: "Mostrar 1 fila",
                            _: "Mostrar %d filas",
                        },
                        pdf: "PDF",
                        print: "Imprimir",
                    },
                    autoFill: {
                        cancel: "Cancelar",
                        fill: "Rellene todas las celdas con <i>%d</i>",
                        fillHorizontal: "Rellenar celdas horizontalmente",
                        fillVertical: "Rellenar celdas verticalmentemente",
                    },
                    decimal: ",",
                    searchBuilder: {
                        add: "Añadir condición",
                        button: {
                            0: "Constructor de búsqueda",
                            _: "Constructor de búsqueda (%d)",
                        },
                        clearAll: "Borrar todo",
                        condition: "Condición",
                        conditions: {
                            date: {
                                after: "Despues",
                                before: "Antes",
                                between: "Entre",
                                empty: "Vacío",
                                equals: "Igual a",
                                notBetween: "No entre",
                                notEmpty: "No Vacio",
                                not: "Diferente de",
                            },
                            number: {
                                between: "Entre",
                                empty: "Vacio",
                                equals: "Igual a",
                                gt: "Mayor a",
                                gte: "Mayor o igual a",
                                lt: "Menor que",
                                lte: "Menor o igual que",
                                notBetween: "No entre",
                                notEmpty: "No vacío",
                                not: "Diferente de",
                            },
                            string: {
                                contains: "Contiene",
                                empty: "Vacío",
                                endsWith: "Termina en",
                                equals: "Igual a",
                                notEmpty: "No Vacio",
                                startsWith: "Empieza con",
                                not: "Diferente de",
                            },
                            array: {
                                not: "Diferente de",
                                equals: "Igual",
                                empty: "Vacío",
                                contains: "Contiene",
                                notEmpty: "No Vacío",
                                without: "Sin",
                            },
                        },
                        data: "Data",
                        deleteTitle: "Eliminar regla de filtrado",
                        leftTitle: "Criterios anulados",
                        logicAnd: "Y",
                        logicOr: "O",
                        rightTitle: "Criterios de sangría",
                        title: {
                            0: "Constructor de búsqueda",
                            _: "Constructor de búsqueda (%d)",
                        },
                        value: "Valor",
                    },
                    searchPanes: {
                        clearMessage: "Borrar todo",
                        collapse: {
                            0: "Paneles de búsqueda",
                            _: "Paneles de búsqueda (%d)",
                        },
                        count: "{total}",
                        countFiltered: "{shown} ({total})",
                        emptyPanes: "Sin paneles de búsqueda",
                        loadMessage: "Cargando paneles de búsqueda",
                        title: "Filtros Activos - %d",
                    },
                    select: {
                        1: "%d fila seleccionada",
                        _: "%d filas seleccionadas",
                        cells: {
                            1: "1 celda seleccionada",
                            _: "$d celdas seleccionadas",
                        },
                        columns: {
                            1: "1 columna seleccionada",
                            _: "%d columnas seleccionadas",
                        },
                    },
                    thousands: ".",
                    datetime: {
                        previous: "Anterior",
                        next: "Proximo",
                        hours: "Horas",
                        minutes: "Minutos",
                        seconds: "Segundos",
                        unknown: "-",
                        amPm: ["am", "pm"],
                    },
                    editor: {
                        close: "Cerrar",
                        create: {
                            button: "Nuevo",
                            title: "Crear Nuevo Registro",
                            submit: "Crear",
                        },
                        edit: {
                            button: "Editar",
                            title: "Editar Registro",
                            submit: "Actualizar",
                        },
                        remove: {
                            button: "Eliminar",
                            title: "Eliminar Registro",
                            submit: "Eliminar",
                            confirm: {
                                _: "¿Está seguro que desea eliminar %d filas?",
                                1: "¿Está seguro que desea eliminar 1 fila?",
                            },
                        },
                        error: {
                            system:
                                'Ha ocurrido un error en el sistema (<a target="\\" rel="\\ nofollow" href="\\">Más información&lt;\\/a&gt;).</a>',
                        },
                        multi: {
                            title: "Múltiples Valores",
                            info: "Los elementos seleccionados contienen diferentes valores para este registro. Para editar y establecer todos los elementos de este registro con el mismo valor, hacer click o tap aquí, de lo contrario conservarán sus valores individuales.",
                            restore: "Deshacer Cambios",
                            noMulti:
                                "Este registro puede ser editado individualmente, pero no como parte de un grupo.",
                        },
                    },
                    info: "Mostrando de _START_ a _END_ de _TOTAL_ entradas",
                },
            });
        });
    </script>

}