PresentationLayer/Controllers/CodigoDocumentoController.cs
using EntitiesLayer;
using LogicBusinessLayer;
using System.Collections.Generic;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    [Authorize]
    public class CodigoDocumentoController : Controller
    {
        CodigoDocumentoBusiness documentoBusiness = new CodigoDocumentoBusiness();
        // GET: CodigoDocumento
        public ActionResult Index()
        {
            return View(documentoBusiness.ShowDocumentsCode());
        }

        // GET: CodigoDocumento/Create
        public ActionResult Create()
        {
            var departamentos = new DepartamentosBusiness();

            var list = departamentos.ShowDepartments();

            List<SelectListItem> items = list.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.Nombre,
                    Value = a.ID.ToString(),
                    Selected = true
                };
            });

            ViewBag.Origen = items;
            ViewBag.Destino = items;

            return View();
        }

        // POST: CodigoDocumento/Create
        [HttpPost]
        public ActionResult Create(Codigo_Documento codigo_Documento)
        {
            try
            {
                documentoBusiness.InsertDocumentCode(codigo_Documento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CodigoDocumento/Edit/5
        public ActionResult Edit(int id)
        {
            var departamentos = new DepartamentosBusiness();

            var list = departamentos.ShowDepartments();

            List<SelectListItem> items = list.ConvertAll(a =>
            {
                return new SelectListItem()
                {
                    Text = a.Nombre,
                    Value = a.ID.ToString(),
                    Selected = true
                };
            });

            ViewBag.Origen = items;
            ViewBag.Destino = items;

            return View(documentoBusiness.FindCodigo(id));
        }

        // POST: CodigoDocumento/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, [Bind(Include = "ID,FechaDoc,UserCorreo,Departamento_Origen,Departamento_Destino,Secuencia")] Codigo_Documento codigo_Documento)
        {
            try
            {
                documentoBusiness.UpDateDocumentCode(codigo_Documento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CodigoDocumento/Delete/5
        public ActionResult Delete(int id)
        {
            return View(documentoBusiness.FindCodigo(id));
        }

        // POST: CodigoDocumento/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Codigo_Documento codigo_Documento)
        {
            try
            {
                documentoBusiness.DeleteDocumentCode(codigo_Documento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PresentationLayer/Views/CodigoDocumento/Create.cshtml
@model EntitiesLayer.Codigo_Documento

@{
    ViewBag.Title = "Crear";

    List<SelectListItem> Origen = (List<SelectListItem>)ViewBag.Origen;
    List<SelectListItem> Destino = (List<SelectListItem>)ViewBag.Destino;

}

<h2 class="display-3 my-3 text-center">Crear Secuencia</h2>

<div class="row justify-content-center">
    <div class="col-12 col-md-8">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                <div class="form-group">
                    <div class="col">
                        <span class="text-muted font-weight-bolder">Fecha: </span>
                        @Html.EditorFor(model => model.FechaDoc, new { htmlAttributes = new { @class = "form-control", type = "date", placeholder = "Fecha" } })
                        @Html.ValidationMessageFor(model => model.FechaDoc, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        <span class="text-muted font-weight-bolder">Usuario: </span>
                        @Html.EditorFor(model => model.UserCorreo, new { htmlAttributes = new { @class = "form-control", type = "email", placeholder = "Usuario" } })
                        @Html.ValidationMessageFor(model => model.UserCorreo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        <span class="text-muted font-weight-bolder">Departamento Origen: </span>
                        @Html.DropDownListFor(model => model.Departamento_Origen, Origen, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Departamento_Origen, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col">
                        <span class="text-muted font-weight-bolder">Departamento Destino: </span>
                        @Html.DropDownListFor(model => model.Departamento_Destino, Destino, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Departamento_Destino, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <div class="col">
                        <input type="submit" value="Crear" class="btn btn-primary btn-block" />
                        <a href="/CodigoDocumento/Index" class="btn btn-primary btn-block">Volver</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/CodigoDocumento/Delete.cshtml
@model EntitiesLayer.Codigo_Documento

@{
    ViewBag.Title = "Delete";
}

<h2 class="display-3 my-3 text-center">Eliminar Secuencia</h2>
<div class="row justify-content-center">
    <div class="col-12 d-flex justify-content-center">
        <div class="card text-white bg-danger mb-3" style="max-width: 20rem;">
            <div class="card-header">Eliminar</div>
            <div class="card-body">
                <h5 class="card-title">
                    @Html.DisplayNameFor(model => model.FechaDoc):

                    @Convert.ToDateTime(Model.FechaDoc).ToString("dddd, dd MMMM yyyy")

                    <br />

                    @Html.DisplayNameFor(model => model.UserCorreo):

                    @Html.DisplayFor(model => model.UserCorreo)

                    <br />

                    @Html.DisplayNameFor(model => model.Secuencia):

                    @Html.DisplayFor(model => model.Secuencia)

                </h5>
                <p class="card-text">¿Está seguro de que desea eliminar? Una vez hecho no podra recuperar los datos.</p>
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" />
            <a href="/CodigoDocumento/Index" class="btn btn-primary">Volver</a>
        </div>
    }
</div>

PresentationLayer/Views/CodigoDocumento/Edit.cshtml
@model EntitiesLayer.Codigo_Documento

@{
    ViewBag.Title = "Editar";

    List<SelectListItem> Origen = (List<SelectListItem>)ViewBag.Origen;
    List<SelectListItem> Destino = (List<SelectListItem>)ViewBag.Destino;
}

<h2 class="display-3 my-3 text-center">Editar Secuencia</h2>

<div class="row justify-content-center">
    <div class="col-12 col-md-8">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.HiddenFor(model => model.ID)

            <div class="form-group">
                <div class="col">
                    <span class="text-muted font-weight-bolder">Fecha: </span>
                    @Html.EditorFor(model => model.FechaDoc, new { htmlAttributes = new { @class = "form-control", type ="date" } })
                    @Html.ValidationMessageFor(model => model.FechaDoc, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col">
                    <span class="text-muted font-weight-bolder">Usuario: </span>
                    @Html.EditorFor(model => model.UserCorreo, new { htmlAttributes = new { @class = "form-control", type="email", placeholder="Usuario" } })
                    @Html.ValidationMessageFor(model => model.UserCorreo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col">
                    <span class="text-muted font-weight-bolder">Departamento Origen: </span>
                    @Html.DropDownListFor(model => model.Departamento_Origen, Origen, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Departamento_Origen, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col">
                    <span class="text-muted font-weight-bolder">Departamento Destino: </span>
                    @Html.DropDownListFor(model => model.Departamento_Destino, Destino, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Departamento_Destino, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                <div class="col">
                    <input type="submit" value="Editar" class="btn btn-block btn-success" />
                    <a href="/CodigoDocumento/Index" class="btn btn-primary btn-block">Volver</a>

                </div>
            </div>
        </div>
        }
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PresentationLayer/Views/CodigoDocumento/Index.cshtml
@model IEnumerable<EntitiesLayer.VistaSecuencia_Result>

@{
    ViewBag.Title = "Secuencia de Documentos";
}


<h2 class="display-2 my-3">Secuencia de Documentos</h2>

<div class="my-2">

    <a href="/CodigoDocumento/Create" class="btn btn-primary">Crear</a>

</div>

<table class="table table-borderless table-hover">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FechaDoc).ToString()
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserCorreo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departamento_Origen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departamento_Destino)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Secuencia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Convert.ToDateTime(item.FechaDoc).ToString("dddd, dd MMMM yyyy")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserCorreo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departamento_Origen)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Departamento_Destino)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Secuencia)
                </td>
                <td class="d-flex">
                    <a href="@Url.Action("Edit", "CodigoDocumento")/@item.ID" class="btn btn-success ml-1">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <a href="@Url.Action("Delete", "CodigoDocumento")/@item.ID" class="btn btn-danger ml-1">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>

</table>

@section scripts{

    <script>

        $(document).ready(function () {
            $(".table").DataTable({
                language: {
                    processing: "Procesando...",
                    lengthMenu: "Mostrar _MENU_ registros",
                    zeroRecords: "No se encontraron resultados",
                    emptyTable: "Ningún dato disponible en esta tabla",
                    infoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    infoFiltered: "(filtrado de un total de _MAX_ registros)",
                    search: "Buscar:",
                    infoThousands: ",",
                    loadingRecords: "Cargando...",
                    paginate: {
                        first: "Primero",
                        last: "Último",
                        next: "Siguiente",
                        previous: "Anterior",
                    },
                    aria: {
                        sortAscending: ": Activar para ordenar la columna de manera ascendente",
                        sortDescending:
                            ": Activar para ordenar la columna de manera descendente",
                    },
                    buttons: {
                        copy: "Copiar",
                        colvis: "Visibilidad",
                        collection: "Colección",
                        colvisRestore: "Restaurar visibilidad",
                        copyKeys:
                            "Presione ctrl o u2318 + C para copiar los datos de la tabla al portapapeles del sistema. <br /> <br /> Para cancelar, haga clic en este mensaje o presione escape.",
                        copySuccess: {
                            1: "Copiada 1 fila al portapapeles",
                            _: "Copiadas %d fila al portapapeles",
                        },
                        copyTitle: "Copiar al portapapeles",
                        csv: "CSV",
                        excel: "Excel",
                        pageLength: {
                            "-1": "Mostrar todas las filas",
                            1: "Mostrar 1 fila",
                            _: "Mostrar %d filas",
                        },
                        pdf: "PDF",
                        print: "Imprimir",
                    },
                    autoFill: {
                        cancel: "Cancelar",
                        fill: "Rellene todas las celdas con <i>%d</i>",
                        fillHorizontal: "Rellenar celdas horizontalmente",
                        fillVertical: "Rellenar celdas verticalmentemente",
                    },
                    decimal: ",",
                    searchBuilder: {
                        add: "Añadir condición",
                        button: {
                            0: "Constructor de búsqueda",
                            _: "Constructor de búsqueda (%d)",
                        },
                        clearAll: "Borrar todo",
                        condition: "Condición",
                        conditions: {
                            date: {
                                after: "Despues",
                                before: "Antes",
                                between: "Entre",
                                empty: "Vacío",
                                equals: "Igual a",
                                notBetween: "No entre",
                                notEmpty: "No Vacio",
                                not: "Diferente de",
                            },
                            number: {
                                between: "Entre",
                                empty: "Vacio",
                                equals: "Igual a",
                                gt: "Mayor a",
                                gte: "Mayor o igual a",
                                lt: "Menor que",
                                lte: "Menor o igual que",
                                notBetween: "No entre",
                                notEmpty: "No vacío",
                                not: "Diferente de",
                            },
                            string: {
                                contains: "Contiene",
                                empty: "Vacío",
                                endsWith: "Termina en",
                                equals: "Igual a",
                                notEmpty: "No Vacio",
                                startsWith: "Empieza con",
                                not: "Diferente de",
                            },
                            array: {
                                not: "Diferente de",
                                equals: "Igual",
                                empty: "Vacío",
                                contains: "Contiene",
                                notEmpty: "No Vacío",
                                without: "Sin",
                            },
                        },
                        data: "Data",
                        deleteTitle: "Eliminar regla de filtrado",
                        leftTitle: "Criterios anulados",
                        logicAnd: "Y",
                        logicOr: "O",
                        rightTitle: "Criterios de sangría",
                        title: {
                            0: "Constructor de búsqueda",
                            _: "Constructor de búsqueda (%d)",
                        },
                        value: "Valor",
                    },
                    searchPanes: {
                        clearMessage: "Borrar todo",
                        collapse: {
                            0: "Paneles de búsqueda",
                            _: "Paneles de búsqueda (%d)",
                        },
                        count: "{total}",
                        countFiltered: "{shown} ({total})",
                        emptyPanes: "Sin paneles de búsqueda",
                        loadMessage: "Cargando paneles de búsqueda",
                        title: "Filtros Activos - %d",
                    },
                    select: {
                        1: "%d fila seleccionada",
                        _: "%d filas seleccionadas",
                        cells: {
                            1: "1 celda seleccionada",
                            _: "$d celdas seleccionadas",
                        },
                        columns: {
                            1: "1 columna seleccionada",
                            _: "%d columnas seleccionadas",
                        },
                    },
                    thousands: ".",
                    datetime: {
                        previous: "Anterior",
                        next: "Proximo",
                        hours: "Horas",
                        minutes: "Minutos",
                        seconds: "Segundos",
                        unknown: "-",
                        amPm: ["am", "pm"],
                    },
                    editor: {
                        close: "Cerrar",
                        create: {
                            button: "Nuevo",
                            title: "Crear Nuevo Registro",
                            submit: "Crear",
                        },
                        edit: {
                            button: "Editar",
                            title: "Editar Registro",
                            submit: "Actualizar",
                        },
                        remove: {
                            button: "Eliminar",
                            title: "Eliminar Registro",
                            submit: "Eliminar",
                            confirm: {
                                _: "¿Está seguro que desea eliminar %d filas?",
                                1: "¿Está seguro que desea eliminar 1 fila?",
                            },
                        },
                        error: {
                            system:
                                'Ha ocurrido un error en el sistema (<a target="\\" rel="\\ nofollow" href="\\">Más información&lt;\\/a&gt;).</a>',
                        },
                        multi: {
                            title: "Múltiples Valores",
                            info: "Los elementos seleccionados contienen diferentes valores para este registro. Para editar y establecer todos los elementos de este registro con el mismo valor, hacer click o tap aquí, de lo contrario conservarán sus valores individuales.",
                            restore: "Deshacer Cambios",
                            noMulti:
                                "Este registro puede ser editado individualmente, pero no como parte de un grupo.",
                        },
                    },
                    info: "Mostrando de _START_ a _END_ de _TOTAL_ entradas",
                },
            });
        });
    </script>

}